<?php
ob_start();
// Eski hali: require_once 'baglan.php';
// Yeni hali (Tam yol gösteriyoruz):
require_once __DIR__ . '/baglan.php';

ob_end_clean();

// --- AYARLAR & HAVUZLAR ---
$anonimIsimler = [
    // --- Orijinal Liste ---
    "ShadowCrawler",
    "GhostProtocol",
    "CyberPunk88",
    "Matrix_Neo",
    "GamerGirl92",
    "Anonymous_User",
    "CodeBreaker",
    "Berserk_Guts",
    "Phantom",
    "RetroGamer",
    "Zenith_Player",
    "VoidWalker",
    "PixelHunter",
    "DriftKing",
    "Nebula",
    "NetRunner_X",
    "ZeroDay_Exploit",
    "KernelPanic",
    "DeepPacket",
    "RootAccess",
    "CyberSpectre",
    "BinaryGod",
    "ProxyGhost",
    "DataWraith",
    "BlackHat_Vibe",
    "LogicBomb",
    "NeuralLink",
    "SubLayer",
    "PacketSniffer",
    "OverClocked",
    "Eclipse_Born",
    "Struggle_Gaze",
    "BlackSwordsman",
    "Behelit_Path",
    "ApostleHunter",
    "Crimson_Egg",
    "Falcon_Shadow",
    "Nightmare_Slayer",
    "Inner_Beast",
    "MarkOfDoom",
    "DiffCheck",
    "NexusSeizer",
    "CarryProtocol",
    "SkillShot_God",
    "SoloCarry_Only",
    "LastHit_Master",
    "VisionScore",
    "FogOfWar_0",
    "EloHell_Survivor",
    "DraftKing",
    "LaneBully",
    "ClutchFactor",
    "AbyssWatcher",
    "Singularity_Point",
    "EventHorizon",
    "VoidEcho",
    "DarkMatter_99",
    "Stellar_Phantom",
    "Cosmic_Ruin",
    "NovaSlayer",
    "Infinite_Void",
    "Shadow_Aura",
    "Nightfall_Op",
    "Obsidian_Soul",
    "DartVader",
    "HotReload_X",
    "WidgetMaster",
    "State_Manager",
    "LegacyCode",
    "GitPush_Force",
    "Async_Soul",
    "NullPointer",
    "Retro_Flux",
    "Pixel_Vandal",
    "BitCrusher",
    "CyberOutlaw",
    "Vortex_Rider",
    "Neon_Ronin",
    "Glitch_Hunter",

    // --- Genişletilmiş Liste (500+ Toplam) ---
    "Acid_Rain",
    "AfterShock",
    "Alpha_Omega",
    "Amber_Void",
    "Ancient_Glitch",
    "Anomaly_X",
    "Apex_Predator",
    "Aqua_Ghost",
    "Arcane_Zero",
    "Archive_Slayer",
    "Ashen_One",
    "Astral_Drift",
    "Atlas_Rise",
    "Atomic_Neon",
    "Audio_Vandal",
    "Azure_Sky",
    "Bad_Sector",
    "Bandwidth_Hog",
    "Bane_Of_Mid",
    "Baron_Stealer",
    "Battery_Low",
    "Beat_Maker",
    "Berserk_Mode",
    "Beta_Tester",
    "Beyond_Evil",
    "Bio_Hazard",
    "Bit_Legend",
    "Black_Box",
    "Black_Ice",
    "Blade_Runner",
    "Bleeding_Edge",
    "Blind_Spot",
    "Blizzard_Soul",
    "Blood_Moon",
    "Blue_Screen",
    "Bolt_Action",
    "Bone_Cracker",
    "Brain_Dead",
    "Broken_Logic",
    "Buff_Me",
    "Bullet_Time",
    "Burn_Rate",
    "Byte_Size",
    "Carbon_Copy",
    "Chaos_Theory",
    "Chrome_Spirit",
    "Cinder_Ash",
    "Circuit_Breaker",
    "City_Viper",
    "Cloud_Nine",
    "Coalition_X",
    "Code_Green",
    "Cold_Steel",
    "Combat_Ready",
    "Cmd_Prompt",
    "Complex_Mind",
    "Cookie_Cutter",
    "Copper_Head",
    "Core_Dump",
    "Cortex_Error",
    "Cosmic_Dust",
    "Crash_Dummy",
    "Critical_Hit",
    "Crow_Control",
    "Cryptic_Msg",
    "Crystal_Clear",
    "Cyber_Dragon",
    "Cyber_Monk",
    "Cyborg_Eye",
    "Dark_Web",
    "Data_Drain",
    "Day_Walker",
    "Dead_Code",
    "Deadlock_User",
    "Death_Note",
    "Deep_Fake",
    "Deep_Freeze",
    "Default_User",
    "Delete_All",
    "Desert_Fox",
    "Dev_Mode",
    "Diamond_Hand",
    "Digital_Nomad",
    "Distort_View",
    "Divine_Touch",
    "Docker_Container",
    "Doom_Bringer",
    "Double_Kill",
    "Down_Time",
    "Dragon_Born",
    "Dread_Knight",
    "Dream_State",
    "Drop_Table",
    "Dust_To_Dust",
    "Dying_Light",
    "Echo_Loc",
    "Elastic_Search",
    "Electric_Sheep",
    "Element_Zero",
    "Emerald_Eye",
    "Empty_Set",
    "End_Game",
    "End_Of_Line",
    "Entropy_X",
    "Escape_Key",
    "Eternal_Dark",
    "Ether_Ghost",
    "Evil_Twin",
    "Evolution_X",
    "Excalibur",
    "Exit_Strategy",
    "Factorial_Zero",
    "Falling_Star",
    "False_Pos",
    "Fast_Forward",
    "Fatal_Error_88",
    "Fearless_One",
    "Feral_Beast",
    "Fiber_Optic",
    "Final_Boss",
    "Fire_Wall",
    "Flame_War",
    "Flash_Step",
    "Flat_Line",
    "Flicker_Gamer",
    "Flow_State",
    "Force_Field",
    "Forbidden_Code",
    "Forgotten_Soul",
    "Fractal_X",
    "Fragmented_S",
    "Frost_Byte",
    "Full_Stack",
    "Future_Shock",
    "Galaxy_Gate",
    "Gamma_Ray",
    "Gank_Master",
    "Ghost_In_Shell",
    "Giga_Watt",
    "Global_Offensive",
    "Grave_Digger",
    "Gray_Hat",
    "Green_Screen",
    "Grid_Runner",
    "Grim_Reaper",
    "Ground_Zero",
    "Hack_Planet",
    "Half_Life",
    "Halo_Effect",
    "Hard_Drive",
    "Hard_Reset",
    "Healer_Main",
    "Heart_Beat",
    "Heavy_Metal",
    "Hidden_Blade",
    "High_Ping",
    "Horizon_Zero",
    "Host_Machine",
    "Hot_Fix",
    "Hybrid_Theory",
    "Hyper_Link",
    "Ice_Cold",
    "Iconic_Vibe",
    "Idle_Mode",
    "Ignition_X",
    "Illusion_ist",
    "Impact_Factor",
    "Infinite_Loop",
    "In_Output",
    "Insomnia_Dev",
    "Instant_Kill",
    "Internal_Err",
    "Interstellar_X",
    "Into_Void",
    "Iron_Fist",
    "Jade_Dragon",
    "Java_Script",
    "Jungle_Diff",
    "Justice_Bring",
    "Kill_Switch",
    "King_Maker",
    "Knight_Rider",
    "Kraken_Awake",
    "Lag_Switch",
    "Laser_Focus",
    "Last_Action",
    "Lava_Flow",
    "Law_Abiding",
    "Lead_Zeppelin",
    "Legacy_User",
    "Level_Up",
    "Light_Speed",
    "Liquid_Cool",
    "Live_Stream",
    "Load_Balancer",
    "Locked_In",
    "Logic_Gate",
    "Lone_Wolf",
    "Long_Shot",
    "Loop_Back",
    "Lost_Signal",
    "Low_Battery",
    "Lunar_Eclipse",
    "Machine_Gun",
    "Macro_King",
    "Mad_Max",
    "Magic_Wand",
    "Main_Frame",
    "Malware_X",
    "Man_Machine",
    "Marble_Stat",
    "Master_Key",
    "Matrix_Reload",
    "Mega_Mind",
    "Memory_Leak",
    "Mercury_Vibe",
    "Metal_Gear",
    "Micro_Chip",
    "Midnight_Sun",
    "Mind_Map",
    "Mist_Walker",
    "Modder_X",
    "Moon_Light",
    "Mother_Board",
    "Moving_Target",
    "Neon_City",
    "Never_Mind",
    "New_Level",
    "Next_Gen",
    "Night_Owl",
    "Nitro_Fuel",
    "No_Control",
    "No_Mercy",
    "No_Signal",
    "Noise_Level",
    "Nomad_User",
    "Non_Stop",
    "North_Star",
    "Nova_Core",
    "Null_Set",
    "Number_One",
    "Obsidian_X",
    "Ocean_Deep",
    "Off_Grid",
    "Offline_Now",
    "Old_School",
    "Omega_Weapon",
    "On_The_Edge",
    "One_Shot",
    "Open_Source",
    "Operator_X",
    "Optic_Nerve",
    "Orbit_Drift",
    "Outer_Space",
    "Over_Drive",
    "Overflow_Err",
    "Oxygen_Level",
    "Pacific_Blue",
    "Paradox_X",
    "Parallel_Life",
    "Paranoid_Dev",
    "Particle_X",
    "Pass1234",
    "Patch_Notes",
    "Path_Finder",
    "Pentester_V",
    "Phantom_Pain",
    "Phase_Shift",
    "Phoenix_Rise",
    "Pixel_Perfect",
    "Plasma_Burn",
    "Point_Blank",
    "Poison_Ivy",
    "Polaris_X",
    "Power_Up",
    "Pressure_Low",
    "Prime_Time",
    "Priority_One",
    "Private_Key",
    "Programmer_X",
    "Project_X",
    "Protocol_Z",
    "Prototype_0",
    "Pulse_Rate",
    "Pure_Evil",
    "Pyramid_God",
    "Quantum_State",
    "Quark_X",
    "Quartz_Vibe",
    "Quick_Shot",
    "Quiet_Night",
    "Radar_Scan",
    "Radioactive_X",
    "Rage_Quit",
    "Rain_Maker",
    "Ram_Disk",
    "Random_Access",
    "Raw_Data",
    "Reaction_Time",
    "Real_Time",
    "Reboot_System",
    "Red_Line",
    "Red_Point",
    "Redemption_S",
    "Reflection_X",
    "Reflex_Gamer",
    "Reload_Now",
    "Remote_Access",
    "Reset_Btn",
    "Resistance_X",
    "Resolution_H",
    "Resonance_V",
    "Retro_Fit",
    "Reverse_Eng",
    "Rich_Text",
    "Riot_Gear",
    "Rising_Sun",
    "Road_Runner",
    "Robot_Arm",
    "Rogue_One",
    "Root_User_X",
    "Router_Hacker",
    "Rust_Bucket",
    "Safe_Mode",
    "Samurai_Soul",
    "Sand_Box",
    "Satellite_X",
    "Savage_Mode",
    "Scanner_V",
    "Screen_Shot",
    "Script_Kiddie",
    "Search_Light",
    "Second_Life",
    "Secret_Agent",
    "Sector_7",
    "Secure_Layer",
    "Sentinel_X",
    "Server_Side",
    "Shadow_Step",
    "Sharp_Edge",
    "Shield_Wall",
    "Shock_Wave",
    "Short_Circuit",
    "Shotgun_X",
    "Shredder_V",
    "Shutdown_X",
    "Side_Effect",
    "Signal_Lost",
    "Silicon_V",
    "Silver_Surf",
    "Simulated_X",
    "Siren_Call",
    "Skeleton_Key",
    "Sky_Line",
    "Sky_Net",
    "Slash_Burn",
    "Slayer_One",
    "Sleep_Mode",
    "Slide_Rule",
    "Slow_Motion",
    "Smart_Contract",
    "Smoke_Screen",
    "Snake_Eye",
    "Snap_Shot",
    "Snow_Fall",
    "Soft_Ware",
    "Solar_Flare",
    "Solid_State",
    "Sonic_Boom",
    "Soul_Reaper",
    "Sound_Wave",
    "Space_Invader",
    "Space_Time",
    "Spark_Plug",
    "Spectre_X",
    "Speed_Limit",
    "Spider_Web",
    "Spiral_V",
    "Spirit_Wolf",
    "Split_Second",
    "Spy_Ware",
    "Stage_One",
    "Star_Dust",
    "Star_Light",
    "Static_Void",
    "Steam_Eng",
    "Steel_Heart",
    "Storm_Born",
    "Street_Fighter",
    "Sub_Zero",
    "Super_Nova",
    "Surface_X",
    "Surge_Vibe",
    "Switch_Board",
    "Symmetry_X",
    "Synapse_X",
    "System_Crash",
    "Table_Top",
    "Tachyon_V",
    "Tactical_X",
    "Tank_Main",
    "Target_Acq",
    "Task_Master",
    "Tech_Support",
    "Teleport_X",
    "Tempest_V",
    "Terminal_X",
    "Tesla_Coil",
    "The_Architect",
    "The_Beginner",
    "The_Ending",
    "The_Great_X",
    "The_Oracle",
    "Thermal_X",
    "Third_Eye",
    "Thunder_Bolt",
    "Time_Travel",
    "Titanium_X",
    "Top_Secret",
    "Touch_Pad",
    "Toxic_Waste",
    "Tracer_X",
    "Track_Ball",
    "Traffic_Light",
    "Transistor_V",
    "Transmission",
    "Trial_Error",
    "Trigger_Happy",
    "Triple_Kill",
    "Trophy_Hunter",
    "Tsunami_X",
    "Turbo_Charge",
    "Twilight_V",
    "Twin_Turbo",
    "Ultra_Violet",
    "Under_Ground",
    "Unknown_User",
    "Unlimited_X",
    "Update_Now",
    "Uptime_Stat",
    "User_Friendly",
    "Vacuum_V",
    "Valhalla_S",
    "Vampire_V",
    "Vandal_X",
    "Vanguard_V",
    "Vapor_Ware",
    "Vector_X",
    "Velocity_V",
    "Venom_X",
    "Versus_S",
    "Vertex_X",
    "Vibration_V",
    "Video_Game",
    "Viking_S",
    "Virtual_X",
    "Virus_Detected",
    "Vision_X",
    "Visual_V",
    "Void_X",
    "Voltage_V",
    "Volume_X",
    "Vortex_V",
    "Wall_Hack",
    "Warp_Drive",
    "Watch_Dog",
    "Water_Cool",
    "Wave_Form",
    "Web_Master",
    "White_Hat",
    "Wild_Card",
    "Wind_Walker",
    "Wire_Tap",
    "Wireless_X",
    "Wizard_V",
    "Wolf_Pack",
    "Wonder_Land",
    "Work_Flow",
    "World_Order",
    "Wraith_X",
    "Xenon_V",
    "XFactor_V",
    "Yellow_Sub",
    "Zero_Cool",
    "Zero_Gravity",
    "Zero_Tolerance",
    "Zig_Zag",
    "Zodiac_X",
    "Zombie_V",
    "Zone_Out",
    "Abstract_X",
    "Blade_Vibe",
    "Crypto_Wolf",
    "Digital_Zen",
    "Echo_Vortex",
    "Flame_Rider",
    "Grid_Shadow",
    "Hyper_Pulse",
    "Iron_Soul",
    "Jet_Stream",
    "King_Phantom",
    "Lunar_Raven",
    "Mystic_Zero",
    "Neon_Spectre",
    "Orbital_X",
    "Pulse_Hunter",
    "Quantum_Raven",
    "Retro_Vandal",
    "Shadow_Wolf",
    "Titan_X",
    "Urban_Ninja",
    "Void_Wraith",
    "Warp_Rider",
    "Xenon_Night",
    "Zenith_X"
];

// Genel mesajlar (Her zaman dönebilir)
// --- GENEL MESAJLAR (Sohbeti Canlı Tutan Karışık Muhabbetler) ---
$generalMessages = [
    "Anyone online? Looking for some coop partners.",
    "This site is getting better every day, love the new design.",
    "The download speeds are surprisingly fast today.",
    "Greetings from Europe! Found this gem of a site recently.",
    "Is there a discord server for Oniklotho?",
    "Does anyone know if the NSFW section gets daily updates?",
    "Just finished downloading, everything works perfect. Thanks admin!",
    "Who else is refreshing the page waiting for new releases? lol",
    "Can we get a request section? I have a list of old games.",
    "Seed please! Wait, this is direct download... nevermind 😂",
    "Admin, you dropped this 👑",
    "Are you guys using a VPN? My ISP is blocking some links.",
    "Finally a site without 100 popup ads before the actual link.",
    "Server 1 is blazing fast today, hitting 25MB/s!",
    "Is it just me or is the site a bit slow today?",
    "Shoutout to the uploader, doing god's work.",
    "Anyone from Turkey here? Selamlar!",
    "I literally canceled my Netflix for this site.",
    "Please tell me there will be an Android app for Oniklotho.",
    "Just bought a new 2TB HDD just for the games from here.",
    "What's everyone playing/watching this weekend?",
    "Bro, the NSFW section here is actually premium quality 🥵",
    "Can you guys add more seeding servers? Sometimes it drops.",
    "Hello from Brazil! Love the content.",
    "Keep up the good work team!",
    "Anyone online? Looking for some coop partners.",
    "This site is getting better every day, love the new design.",
    "The download speeds are surprisingly fast today.",
    "Greetings from Europe! Found this gem of a site recently.",
    "Is there a discord server for Oniklotho?",
    "Does anyone know if the NSFW section gets daily updates?",
    "Just finished downloading, everything works perfect. Thanks admin!",
    "Who else is refreshing the page waiting for new releases? lol",
    "Can we get a request section? I have a list of old games.",
    "Seed please! Wait, this is direct download... nevermind 😂",
    "Admin, you dropped this 👑",
    "Are you guys using a VPN? My ISP is blocking some links.",
    "Finally a site without 100 popup ads before the actual link.",
    "Server 1 is blazing fast today, hitting 25MB/s!",
    "Is it just me or is the site a bit slow today?",
    "Shoutout to the uploader, doing god's work.",
    "Anyone from Turkey here? Selamlar!",
    "I literally canceled my Netflix for this site.",
    "Please tell me there will be an Android app for Oniklotho.",
    "Just bought a new 2TB HDD just for the games from here.",
    "What's everyone playing/watching this weekend?",
    "Bro, the NSFW section here is actually premium quality 🥵",
    "Can you guys add more seeding servers? Sometimes it drops.",
    "Hello from Brazil! Love the content.",
    "Keep up the good work team!",
    "My ISP blocked this domain, had to use Cloudflare DNS.",
    "Is the VIP membership worth it?",
    "Where can I report a dead link?",
    "Who's the main uploader here? They deserve a medal.",
    "Anyone else staying up till 3 AM downloading stuff?",
    "Wish there was a dark mode... oh wait, it is dark mode!",
    "Just found this site through Reddit. Best discovery of the year.",
    "Does anyone know when the new repacks drop? Is there a schedule?",
    "Is the live chat history saved or does it clear every day?"
];

// --- FİLM ŞABLONLARI (Sinefillerin ve İzleyicilerin Yorumları) ---
$movieTemplates = [
    "I just watched [NAME], the quality was amazing!",
    "Has anyone seen [NAME] yet? Is it worth the watch?",
    "I've been waiting for [NAME] to be added here. Finally!",
    "The player for [NAME] is working smoothly, no lag at all.",
    "Can someone recommend movies similar to [NAME]?",
    "The plot of [NAME] was absolutely mind-blowing.",
    "Are the English subtitles for [NAME] synced properly?",
    "Damn, [NAME] looks so good in 1080p.",
    "Is [NAME] available in 4K yet?",
    "I didn't expect that ending in [NAME]... no spoilers though!",
    "The audio mixing on [NAME] is a bit low, or is it my speakers?",
    "Rewatching [NAME] for the 3rd time, such a masterpiece.",
    "Who else came here just to watch [NAME]?",
    "Link 1 is dead for [NAME], but Link 2 works perfectly.",
    "Does [NAME] have post-credit scenes? Should I keep watching?",
    "The cinematography in [NAME] is crazy good.",
    "Honestly, [NAME] was a bit overhyped. Still a good watch.",
    "Thanks for the fast upload on [NAME], admin!",
    "Can we cast [NAME] to smart TV from this player?",
    "Watching [NAME] right now with some popcorn 🍿",
    "I just watched [NAME], the quality was amazing!",
    "Has anyone seen [NAME] yet? Is it worth the watch?",
    "I've been waiting for [NAME] to be added here. Finally!",
    "The player for [NAME] is working smoothly, no lag at all.",
    "Can someone recommend movies similar to [NAME]?",
    "The plot of [NAME] was absolutely mind-blowing.",
    "Are the English subtitles for [NAME] synced properly?",
    "Damn, [NAME] looks so good in 1080p.",
    "Is [NAME] available in 4K yet?",
    "I didn't expect that ending in [NAME]... no spoilers though!",
    "The audio mixing on [NAME] is a bit low, or is it my speakers?",
    "Rewatching [NAME] for the 3rd time, such a masterpiece.",
    "Who else came here just to watch [NAME]?",
    "Link 1 is dead for [NAME], but Link 2 works perfectly.",
    "Does [NAME] have post-credit scenes? Should I keep watching?",
    "The cinematography in [NAME] is crazy good.",
    "Honestly, [NAME] was a bit overhyped. Still a good watch.",
    "Thanks for the fast upload on [NAME], admin!",
    "Can we cast [NAME] to smart TV from this player?",
    "Watching [NAME] right now with some popcorn 🍿",
    "Is the audio in [NAME] cam quality or direct line?",
    "Can we get Spanish/French subtitles for [NAME]?",
    "The buffering on [NAME] is a bit annoying tonight.",
    "The CGI in [NAME] looks terrible in high-res lol.",
    "Is [NAME] the Director's Cut or theatrical release?",
    "My TV browser doesn't load the player for [NAME]. Any fixes?",
    "Don't read the comments below if you haven't watched [NAME], full of spoilers!"
];

// --- OYUN ŞABLONLARI (Gamer ve Repack Yorumları) ---
$gameTemplates = [
    "Downloading [NAME] right now, can't wait to play!",
    "Does [NAME] support controllers? Or just keyboard/mouse?",
    "Is the [NAME] repack stable? Any crashes?",
    "I played [NAME] for 5 hours straight. Best game ever.",
    "My PC is struggling with [NAME], need an upgrade lol.",
    "If you haven't played [NAME] yet, you are missing out!",
    "Is the multiplayer working for [NAME] or is it offline only?",
    "Where is the save file location for [NAME]? Need to backup.",
    "Getting 60fps on high settings with [NAME], great optimization.",
    "Stuck at 99% installing [NAME], anyone else?",
    "Just a heads up, turn off your antivirus before extracting [NAME].",
    "The crack for [NAME] works perfectly on Windows 11.",
    "Anyone got a good mod list for [NAME]?",
    "Can my GTX 1650 run [NAME]? Thinking about downloading.",
    "[NAME] is way harder than I thought, dying every 5 mins.",
    "Does this version of [NAME] include all the DLCs?",
    "Is [NAME] updated to the latest patch?",
    "Thanks for compressing [NAME], saved me so much bandwidth.",
    "The graphics in [NAME] are insane! Highly recommend.",
    "I'm getting an ISDone.dll error on [NAME], how to fix?",
    "Downloading [NAME] right now, can't wait to play!",
    "Does [NAME] support controllers? Or just keyboard/mouse?",
    "Is the [NAME] repack stable? Any crashes?",
    "I played [NAME] for 5 hours straight. Best game ever.",
    "My PC is struggling with [NAME], need an upgrade lol.",
    "If you haven't played [NAME] yet, you are missing out!",
    "Is the multiplayer working for [NAME] or is it offline only?",
    "Where is the save file location for [NAME]? Need to backup.",
    "Getting 60fps on high settings with [NAME], great optimization.",
    "Stuck at 99.9% installing [NAME], anyone else?",
    "Just a heads up, turn off your antivirus before extracting [NAME].",
    "The crack for [NAME] works perfectly on Windows 11.",
    "Anyone got a good mod list for [NAME]?",
    "Can my GTX 1650 run [NAME]? Thinking about downloading.",
    "[NAME] is way harder than I thought, dying every 5 mins.",
    "Does this version of [NAME] include all the DLCs?",
    "Is [NAME] updated to the latest patch?",
    "Thanks for compressing [NAME], saved me so much bandwidth.",
    "The graphics in [NAME] are insane! Highly recommend.",
    "I'm getting an ISDone.dll error on [NAME], how to fix?",
    "How long does [NAME] take to install? My CPU is cooking.",
    "Getting the unarc.dll error code -11 on [NAME] installation.",
    "Windows Defender flagged the crack for [NAME]. It's a false positive right?",
    "Can I transfer my official Steam save to this cracked version of [NAME]?",
    "Does [NAME] work on Steam Deck / Linux?",
    "Wait, is [NAME] the v1.05 hotfix version?",
    "I keep getting a black screen on startup for [NAME].",
    "Do I need to block [NAME] in my firewall so it doesn't phone home?",
    "Is there a LAN multiplayer fix for [NAME]?",
    "The optimization for [NAME] is trash, getting 20fps on an RTX card."
];

// --- APK MOD ŞABLONLARI (Android Kullanıcılarının Yorumları) ---
$apkTemplates = [
    "Is the [NAME] mod safe to use on my main account?",
    "The premium unlocked features on [NAME] work perfectly!",
    "Does [NAME] require a rooted device?",
    "Thanks for the [NAME] update, the old one was crashing.",
    "Can you get banned for using this [NAME] mod?",
    "Finally, [NAME] without those annoying ads!",
    "Installation for [NAME] was smooth, no parsing errors.",
    "Is the [NAME] mod safe to use on my main account?",
    "The premium unlocked features on [NAME] work perfectly!",
    "Does [NAME] require a rooted device?",
    "Thanks for the [NAME] update, the old one was crashing.",
    "Can you get banned for using this [NAME] mod?",
    "Finally, [NAME] without those annoying ads!",
    "Installation for [NAME] was smooth, no parsing errors.",
    "Do I need to put the OBB file in the Android folder for [NAME]?",
    "The [NAME] mod keeps crashing on Android 14. Any fix?",
    "Are the unlimited coins actually working in [NAME]?",
    "Google Play Protect keeps blocking [NAME], had to turn it off.",
    "Can we sign in with Google on [NAME]? Or just Facebook?",
    "Is [NAME] the arm64-v8a version? Need to know before downloading.",
    "Thanks! Been looking for the VIP version of [NAME] for ages.",
    "The mod menu for [NAME] is hiding behind my notch, can I move it?"
];

// 1. Veritabanından rastgele bir içerik çek (Oyun veya Film)
$sorgu = $db->query("SELECT content_name, content_type FROM contents WHERE content_aktiflik = 1 ORDER BY RAND() LIMIT 1");
$icerik = $sorgu->fetch(PDO::FETCH_ASSOC);

$finalMessage = "";

if ($icerik) {
    $name = $icerik['content_name'];
    $type = $icerik['content_type'];

    // Şans faktörü: %70 içerik konuşsunlar, %30 genel konuşsunlar
    if (rand(1, 10) <= 7) {
        if ($type == 2) { // Film
            $template = $movieTemplates[array_rand($movieTemplates)];
        } elseif ($type == 5) { // APK Mod
            $template = $apkTemplates[array_rand($apkTemplates)];
        } else { // Oyun (Type 1) veya diğerleri
            $template = $gameTemplates[array_rand($gameTemplates)];
        }
        $finalMessage = str_replace("[NAME]", $name, $template);
    } else {
        $finalMessage = $generalMessages[array_rand($generalMessages)];
    }
} else {
    // Veritabanı boşsa genel mesaj at
    $finalMessage = $generalMessages[array_rand($generalMessages)];
}

$rastgeleIsim = $anonimIsimler[array_rand($anonimIsimler)];

// 2. Mesajı Veritabanına Yaz
// bot_chat.php içindeki kayıt kısmını (try bloğunu) bununla değiştir:
try {
    $displayMessage = "<strong>" . $rastgeleIsim . ":</strong> " . $finalMessage;

    $kaydet = $db->prepare("INSERT INTO comments SET
        user_id = :uid,
        content_id = :cid,
        comment_text = :text,
        comment_date = NOW()
    ");

    $insert = $kaydet->execute([
        // DİKKAT: uid değerini 0 yapıyoruz!  
        // Böylece chat_op.php bunu gerçek bir insan sanıp filtrelemeyecek.
        'uid' => 0,
        'cid' => 0,
        'text' => $displayMessage
    ]);

    if ($insert) {
        echo "[SUCCESS]: Message added to General Chat!";
    }
} catch (Exception $e) {
    echo "[ERROR]: " . $e->getMessage();
}